using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IttyBittyProblems
{
    public class CollatzConjecture
    {
        /* A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:
                If even: divide by 2.
                If odd: multiply by 3, then add 1.

          The Collatz algorithm has been tested and found to always reach 1 for all positive integers.
          Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer 
          steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.
          From: https://edabit.com By: persolut*/

        public  int DoCollatz(long a)
        {
            int steps = 0;

            while(a != 1)
            {
                if (a % 2 == 0)
                {
                    a /= 2;
                }
                else
                {
                    a = a * 3 + 1;
                }

                steps++;
            }

            return steps;
        }

        public  string Collatz(long a, long b)
        {
            int stepsA = DoCollatz(a);
            int stepsB = DoCollatz(b);

            return Math.Min(stepsA, stepsB) == stepsA ? "a" : "b"; 
        }
    }
}
